package cmd

import (
	"log/slog"
	"text/template"

	"google.golang.org/protobuf/compiler/protogen"
)

// Run starts running the plugin
func Run() error {
	protogen.Options{}.Run(
		func(gen *protogen.Plugin) error {
			for _, file := range gen.Files {
				if !file.Generate {
					continue
				}
				if err := generateFile(gen, file); err != nil {
					return err
				}
			}
			return nil
		},
	)
	return nil
}

const templ = `
// Code generated by protoc-gen-go-nats. DO NOT EDIT.
// source: {{.GeneratedFilenamePrefix}}.proto

package {{.GoPackageName}}

import (
    "context"
    "log/slog"
    "strings"
    "errors"
    proto "google.golang.org/protobuf/proto"
	nats "github.com/nats-io/nats.go"
	micro "github.com/nats-io/nats.go/micro"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

var tracer = otel.Tracer("{{ .Proto.Name }}")

// handleError is a helper which response with the error.
func handleError(req micro.Request, err error) {
	if sendErr := req.Error("500", err.Error(), nil); sendErr != nil {
		slog.Error(
			"error sending response error",
			slog.String("reason", sendErr.Error()),
			slog.String("subject", req.Subject()),
		)
	}
}

{{ range .Services }}

// NewNATS{{ .GoName }}Server returns the gRPC server as a NATS micro service.
func NewNATS{{ .GoName }}Server(ctx context.Context, nc *nats.Conn, server {{ .GoName }}Server, version, queueGroup string) (micro.Service, error) {
    cfg := micro.Config{
    	Name: "{{ .GoName }}Server",
        Version: version,
        QueueGroup: queueGroup,
        Description: "NATS micro service adaptor wrapping {{ .GoName }}Server",
    }

    srv, err := micro.AddService(nc, cfg)
    if err != nil {
        return nil, err
    }

    logger := slog.With(
     	slog.Group(
      		"service",
        	slog.String("name", cfg.Name),
       		slog.String("version", cfg.Version),
       		slog.String("queue-group", cfg.QueueGroup),
      	),
    )

    {{ range .Methods }}
    logger.Info(
    	"registring endpoint",
     	slog.Group(
      		"endpoint",
        	slog.String("subject", strings.ToLower("svc.{{ .Parent.GoName }}.{{ .GoName }}")),
      	),
    )

    err = srv.AddEndpoint(
        "{{ .Parent.GoName }}",
        micro.ContextHandler(
        	ctx,
        	func(ctx context.Context, req micro.Request){
         		endpointSubject := strings.ToLower("svc.{{ .Parent.GoName }}.{{ .GoName }}")

         		ctx, span := tracer.Start(ctx, "{{ .GoName }}", trace.WithAttributes(attribute.String("subject", endpointSubject)))
           		defer span.End()

	            hlogger := logger.With(
	              	slog.Group(
	               		"endpoint",
	                		slog.String("subject", endpointSubject),
	               	),
	             )

         		r := &{{ .Input.GoIdent.GoName }}{}

           		/*
             		Unmarshal the request.
             	*/
         		if err := proto.Unmarshal(req.Data(), r); err != nil {
           			hlogger.Error("unmarshaling request", slog.String("reason", err.Error()))
           			handleError(req, err)
                	return
                }

                /*
                	Forward on the original request to the original gRPC service.
                */
                resp, err := server.{{ .GoName }}(ctx, r)
                if err != nil {
             		hlogger.Error("service error", slog.String("reason", err.Error()))
             		handleError(req, err)
               		return
                }

                /*
                	Take the response from the gRPC service and dump it as a byte array.
                */
                respDump, err := proto.Marshal(resp)
                if err != nil {
              		hlogger.Error("marshaling response", slog.String("reason", err.Error()))
              		handleError(req, err)
                	return
                }

                /*
                	Finally response with the original response from the gRPC service.
                */
                if err := req.Respond(respDump); err != nil {
              		hlogger.Error("sending response", slog.String("reason", err.Error()))
              		handleError(req, err)
                	return
                }
         	},
        ),
        micro.WithEndpointSubject(strings.ToLower("svc.{{ .Parent.GoName }}.{{ .GoName }}")),
        micro.WithEndpointMetadata(map[string]string{"Description": "TODO: still to be implemented - see .proto file for doco"}),
    )

    if err != nil {
    	logger.Error(
     		"registering endpoint",
       		slog.Group(
         		"endpoint",
           		slog.String("subject", strings.ToLower("svc.{{ .Parent.GoName }}.{{ .GoName }}")),
         	),
       		slog.String("reason", err.Error()),
        )
        return nil, err
    }
    {{ end }}

    return srv, nil
}

// NATS{{ .GoName }}Client is a client connecting to a NATS {{ .GoName }}Server.
type NATS{{ .GoName }}Client struct {
	nc *nats.Conn
}

// NewNATS{{ .GoName }}Client returns a new {{ .GoName }}Server client.
func NewNATS{{ .GoName }}Client(nc *nats.Conn) *NATS{{ .GoName }}Client {
	return &NATS{{ .GoName }}Client{
		nc: nc,
	}
}

{{ range .Methods }}
{{ .Comments.Leading }}func (c *NATS{{ .Parent.GoName }}Client) {{ .GoName }}(ctx context.Context, req *{{ .Input.GoIdent.GoName }}) (*{{ .Output.GoIdent.GoName }}, error) {
	subject := strings.ToLower("svc.{{ .Parent.GoName }}.{{ .GoName }}")

	ctx, span := tracer.Start(ctx, "{{ .GoName }}", trace.WithAttributes(attribute.String("subject", subject)))
	defer span.End()

	payload, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}

	respPayload, err := c.nc.RequestWithContext(ctx, subject, payload)
	if err != nil {
		return nil, err
	}

	rpcError := respPayload.Header.Get(micro.ErrorHeader)
	if rpcError != "" {
		return nil, errors.New(rpcError)
	}

	resp := &{{ .Output.GoIdent.GoName }}{}
	if err := proto.Unmarshal(respPayload.Data, resp); err != nil {
		return nil, err
	}

	return resp, nil
}
{{ end }}

{{ end }}

`

// generateFile generates a .pb.go file.
func generateFile(gen *protogen.Plugin, file *protogen.File) error {

	tmpl, err := template.New("nats-micro-service").Parse(templ)
	if err != nil {
		return err
	}

	if len(file.Services) == 0 {
		// nothing to do here - no services found in this file.
		return nil
	}

	filename := file.GeneratedFilenamePrefix + ".nats.pb.go"
	logger := slog.With("filename", filename)
	logger.Info("generating the files")

	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	if err := tmpl.Execute(g, file); err != nil {
		logger.Error("failed to execute the template", slog.String("reason", err.Error()))
		return err
	}

	return nil
}
